### ISSUE TITLE
InstagramSimpleOAuthViewController dismisses automatically with an error

### ISSUE THREAD

**Issue by josipbernat** [rbaumbach/InstagramSimpleOAuth#10]
Hi,

I'm not sure if this is bug of your library of just a lack of documentation but when I try to present InstagramSimpleOAuthViewController it shows spinner and after few moments callback block gets called with given error:

`Error Domain=NSURLErrorDomain Code=-999 "(null)" UserInfo={NSErrorFailingURLStringKey=https://staticxx.facebook.com/connect/xd_arbiter/r/xaOI6zd9HW9.js?version=42#cb=f117246175298ac&domain=www.instagram.com&origin=https%3A%2F%2Fwww.instagram.com%2Ff325e717a66a4d4&relation=parent&error=unknown_user, NSErrorFailingURLKey=https://staticxx.facebook.com/connect/xd_arbiter/r/xaOI6zd9HW9.js?version=42#cb=f117246175298ac&domain=www.instagram.com&origin=https%3A%2F%2Fwww.instagram.com%2Ff325e717a66a4d4&relation=parent&error=unknown_user})`

I'm sure that cliendID, clientSecret and callbackURL are correct.

**Comment by rbaumbach** [comment]
@josipbernat Thanks for the heads up.  Once I have some free time, I will check it out.

**Comment by ibnusina** [comment]
I have same issue as @josipbernat, the dismiss behavior occur at: 

`
- (void)webView:(UIWebView *)webView didFailLoadWithError:(NSError *)error
{
    if (error.code != 102) {
        [self completeWithError:error];
        
        if (self.shouldShowErrorAlert) {
            [self showErrorAlert:error];
        }
        
        [self dismissViewController];
    }
    
    [self hideProgressHUD];
}
` 
Should the View Controller dismissed on success only? Or should there any additional checking on the error type?

**Comment by dani2906** [comment]
Same issue here. Was this resolved?

**Comment by rbaumbach** [comment]
@ibnusina I have a few issues with your pull request at this point.

1. There seems to be an issue that @josipbernat and @dani2906 are having where they are not being presented with the Instagram login web view.  This is the root issue that needs to be resolved instead of providing a work arounds regarding the handling of the dismissal of the view controller.
2. In regards to the dismissal, there are two schools of thought on how view controllers should be dismissed.  The first being the current implementation (the presented view controller handles it's own dismissal) and the other being that the view controller that presented this controller should also be the view controller that dismisses it.  If the latter is wanted, the dismissal should be done in the completion handler (or using the delegate pattern if that is warranted) in the presenting view controller for both success and failure and dismissal should be removed completely from the presented view controller. Either dismissal for both success and failure are both kept (current implementation), or both dismissals need to be removed.
3. And lastly, I require code coverage for any updates to this library.  This library currently has 100% code coverage and your PR doesn't contain any updates to the tests.  I think your current update will break current tests.

**Comment by wm649548372** [comment]
@rbaumbach Same issue, and sometimes normal sometimes fail, is there the solution？
